name: AWS Deployment Pipeline

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  EC2_INSTANCE_TYPE: t2.micro
  EC2_AMI_ID: ami-09040d770ffe2224f # Update with your preferred AMI ID
  EC2_KEY_NAME: adithi # Update with your key pair name
  S3_BUCKET_NAME: sucessbucket123  # Unique S3 bucket name
  SECURITY_GROUP_ID: sg-0f931dcdc05d8ecd6 # Replace with your security group ID

jobs:
  create-resources:
    name: Create AWS Resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Check if S3 bucket exists
        id: check_s3
        run: |
          if aws s3api head-bucket --bucket ${{ env.S3_BUCKET_NAME }} 2>/dev/null; then
            echo "S3 bucket exists"
            echo "S3_BUCKET_EXISTS=true" >> $GITHUB_ENV
          else
            echo "S3 bucket does not exist"
            echo "S3_BUCKET_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create S3 bucket if not exists
        if: env.S3_BUCKET_EXISTS == 'false'
        run: |
          aws s3 mb s3://${{ env.S3_BUCKET_NAME }} --region ${{ env.AWS_REGION }}

      - name: Check for existing EC2 instance
        id: check_instance
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=myvm" "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].InstanceId" --output text)
          if [ -z "$INSTANCE_ID" ]; then
            echo "Instance does not exist."
            echo "INSTANCE_EXISTS=false" >> $GITHUB_ENV
          else
            echo "Instance exists."
            echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
            echo "INSTANCE_EXISTS=true" >> $GITHUB_ENV
          fi

      - name: Create EC2 instance if not exists
        if: env.INSTANCE_EXISTS == 'false'
        id: create_instance
        run: |
          INSTANCE_ID=$(aws ec2 run-instances --image-id ${{ env.EC2_AMI_ID }} --count 1 --instance-type ${{ env.EC2_INSTANCE_TYPE }} --key-name ${{ env.EC2_KEY_NAME }} --security
